# -*- coding: utf-8 -*-
"""CODE4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vBCAz2x8lvwmNNG2jLDfKuaP8JBu2qfw
"""

marks=[88,90,55,221,41]
print(marks[1:4])
print(marks[:3])
print(marks[-3:-1])
print(marks[0:len(marks)])

movie=[]
movie.append("3 idiot")
movie.append("tere naam")
movie.append("saiyara")
print(movie)

tuple=("a","b","a","d","b",)
tuple.count("a")

list=["a","b","a","d","b"]
list.sort()
print(list)

